# Generated by Django 3.1.7 on 2021-07-19 12:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HowCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CASH', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhereCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='LOCALSHOP', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.FloatField(default=0.0)),
                ('tags', models.CharField(max_length=500)),
                ('how', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.howcategory')),
                ('where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.wherecategory')),
            ],
        ),
    ]
